packaging_format = 2

id = "grafana_v12"
name = "Grafana v12"
description.en = "Metric & analytic dashboards for monitoring"
description.fr = "Tableaux de bord de supervision"

version = "12.1.0~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-only"
website = "https://grafana.com/"
demo = "https://play.grafana.org"
code = "https://github.com/grafana/grafana"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.path]
	type = "path"
	default = "/grafana"

	[install.init_main_permission]
	type = "group"
	default = "visitors"

[resources]
	[resources.sources]

		[resources.sources.main]
		url = "https://dl.grafana.com/grafana/release/12.1.2/grafana_12.1.2_17957162798_linux_amd64.tar.gz"
		sha256 = "4ca51d7f3af7e0c2ff048beba0683a01e781f4153edd8b1a00ce78e61ac0e9b9"
		format = "tar.gz"
		in_subdir = true
		extract = true
		rename = "grafana"

		# needs https://github.com/YunoHost/apps_tools/pull/50
		# autoupdate.strategy = "latest_webpage_link"
		# autoupdate.upstream = "https://grafana.com/grafana/download?edition=oss&pg=oss-graf&platform=linux"
		# autoupdate.version_regex = "^https:\\/\\/dl.grafana.com\\/grafana\\/release\\/(\\d+.\\d+.\\d+)\\/grafana_\\1_\\d+_linux_amd64.tar.gz"

		[resources.sources.arm64]
		url = "https://dl.grafana.com/grafana/release/12.1.2/grafana_12.1.2_17957162798_linux_arm64.tar.gz"
		sha256 = "725e01322d3fd178bb78d6d4f11bbdecad3a222b3b1e6e66a4c432e425003f79"
		format = "tar.gz"
		in_subdir = true
		extract = true
		rename = "grafana"

		# needs https://github.com/YunoHost/apps_tools/pull/50
		# autoupdate.strategy = "latest_webpage_link"
		# autoupdate.upstream = "https://grafana.com/grafana/download?edition=oss&pg=oss-graf&platform=arm"
		# autoupdate.version_regex = "^https:\\/\\/dl.grafana.com\\/grafana\\/release\\/(\\d+.\\d+.\\d+)\\/grafana_\\1_\\d+_linux_arm64.tar.gz"

	[resources.system_user]
	allow_email = true

	[resources.install_dir]

	[resources.data_dir]

	[resources.ports]
    main.default = 3000

	[resources.permissions]
	main.url = "/"

	[resources.apt]
	packages = "mariadb-server"

	[resources.database]
	type = "mysql"
